export const SAVE_CATEGORIES = 'SAVE_CATEGORIES';
export const SAVE_PRODUCTS = 'SAVE_PRODUCTS';
export const SAVE_VENDORS = 'SAVE_VENDORS';

export const SET_PRODUCTS_FILTER = 'SET_PRODUCTS_FILTER';
export const SET_ERROR_CATEGORY = 'SET_ERROR_CATEGORY';
export const SET_LOADING_CATEGORY = 'SET_LOADING_CATEGORY';
export const SET_LOADING_CATALOGUE = 'SET_LOADING_CATALOGUE';
export const SET_ERROR_CATALOGUE = 'SET_ERROR_CATALOGUE';
export const SET_SELECTED_CATEGORY = 'SET_SELECTED_CATEGORY';
